### ISSUE TITLE
Icebreakers and Hangouts - Component styling

### ISSUE THREAD

**Issue by gav228** [UltimateSoftware/fg-mobile#20]
As a user I would like to see a chapter's Icebreakers
[1]

- When: A user is registered, and is also registered to a chapter
- Then: The user is able to see the Icebreakers of that chapter
[2]

- When: A user clicks on the icebreaker
- Then: I will be navigated to the tab of the icebreaker, with a way to go back

![image](https://user-images.githubusercontent.com/42977569/52729828-ef191680-2f87-11e9-86db-745b80d68b30.png)

![image](https://user-images.githubusercontent.com/42977569/52729716-ba0cc400-2f87-11e9-9b3b-343f30a44059.png)

**Comment by markd315** [comment]
To get a list of ALL icebreakers, try this request

```
curl -X GET \
  http://localhost:5000/icebreakers \
  -H 'Postman-Token: aeebe547-64c1-4d3f-a368-78d141751a08' \
  -H 'cache-control: no-cache'
```

Your response will be a list like this:

```
[
    {
        "name": "Icebreaker Numero Uno",
        "description": "Description of the ice-breaking activity",
        "id": "f769d790-a7a0-430e-899b-38d061588110"
    }
]
```

Relationships between an icebreaker and a chapter are not well-defined at the moment, we can talk about how to do this better and create tickets if necessary.

One workaround might be to get a list of hangouts for a chapter like this (which each include info about icebreakers):

```
curl -X GET \
  http://localhost:5000/hangouts/chapter/9d730767-98a7-4a79-b239-48e151c33889 \
  -H 'Postman-Token: 25090460-d1f9-4d3d-8da5-f64d5ba8608a' \
  -H 'cache-control: no-cache'
```
which will return data in the form

```
[
    {
        "date": "2020-01-01",
        "chapterId": "950573fe-d9c7-4575-8528-82cec1ccc77b",
        "description": "Description of the hangout and all its fun stuff.",
        "id": "bfa5b6bf-5e62-423f-aa1f-2d2cd1ff29e1",
        "state": "Unpublished",
        "title": "Hangout Title",
        "icebreakers": []
    },
    {
        "date": "2020-01-01",
        "chapterId": "950573fe-d9c7-4575-8528-82cec1ccc77b",
        "description": "Description of the hangout and all its fun stuff.",
        "id": "82532e09-7083-4565-98e2-bff78ec1915b",
        "state": "Unpublished",
        "title": "Hangout Title",
        "icebreakers": [
            "Icebreaker Numero Uno"
        ]
    }
]
```
filter out any duplicates from the arrays of icebreaker names, and then filter the original list to include only those icebreakers.
