### ISSUE TITLE
Create 'Create Event' functionality

### ISSUE THREAD

**Issue by juansuh** [UltimateSoftware/fg-mobile#32]
Add a button on the events page, only accessible by roles which can create events, which allows the user to create an event. 

- When a user presses the 'create event' button

- Then a popup form should appear that allows the user to create a custom event

- When a user correctly fills out the form for creating an event

- Then an event should be created, with the popup disappearing

- When a user fails to correctly fill out the form for creating an event

- Then a warning should appear

Styling should remain fairly consistent with the rest of the application but is not within the scope of this issue.

**Comment by juansuh** [comment]
https://xd.adobe.com/spec/9d4c3878-cc8e-4d6b-686d-de58e4596cff-eb7d/

**Comment by audgster** [comment]
Closing for new issues
