### ISSUE TITLE
Create Events landing page

### ISSUE THREAD

**Issue by gdeehl** [UltimateSoftware/fg-mobile#41]
Overview: Implement Wix Calendar Widget

Once navigated to Events Tab, have Events icon selected and be able to View and Interact with Events 

- Find an existing react native component that allows users to view events on a calendar
i.e. The Agenda Widget [https://github.com/wix/react-native-calendars] 
- Implement the agenda widget on the Events page
- Add mock event data for user to interact with

**Comment by diazlauren** [comment]
- calendar/agenda view implemented on event landing page
- working on functionality to view an event's details as an expanding panel

**Comment by cheffley6** [comment]
- making agenda default to current date w/ persistence

**Comment by janae225** [comment]
- add event "+" button created

- working on modal popup functionality

**Comment by audgster** [comment]
PR Merged.
