### ISSUE TITLE
Create and implement "View Profile" Component

### ISSUE THREAD

**Issue by audgster** [UltimateSoftware/fg-mobile#44]
Create a component to view a profile.

The component should have
1. The profile banner
2. The circle icon profile picture
3. a gear that will open a settings menu (Doesn't need to show it for this story)
4. Basic profile information, as stored by the backend

Component should be reusable for other parts of the application that may need to display a profile.

![image](https://user-images.githubusercontent.com/3604478/59452992-f25ccb80-8ddc-11e9-9c73-3a234bb7fa8f.png)

**Comment by chandlerMo** [comment]
![image](https://user-images.githubusercontent.com/50677456/60357107-b6ab2f80-99a0-11e9-92db-6699685b1919.png)
![image](https://user-images.githubusercontent.com/50677456/60357119-c0cd2e00-99a0-11e9-852f-33862035d2e9.png)
Completed basic structure of profile

**Comment by audgster** [comment]
PR Merged.
