### ISSUE TITLE
Create Chapter Landing Page

### ISSUE THREAD

**Issue by gdeehl** [UltimateSoftware/fg-mobile#45]
When user navigates to chapter, see chapter information
- Create components for History, Leaders, Mission, Organization Bylaws, Chapter Bylaws
- Use mock data to populate components
Update:
- Added sections to the page with filler text
- Need to fix styling

<img width="327" alt="Screen Shot 2019-06-13 at 1 31 03 PM" src="https://user-images.githubusercontent.com/9449522/59454245-a8291980-8ddf-11e9-8ef1-274a2e5639a9.png">
<img width="325" alt="Screen Shot 2019-06-13 at 1 31 24 PM" src="https://user-images.githubusercontent.com/9449522/59454258-abbca080-8ddf-11e9-9ff9-596d2f55d02e.png">
<img width="326" alt="Screen Shot 2019-06-13 at 1 31 32 PM" src="https://user-images.githubusercontent.com/9449522/59454264-afe8be00-8ddf-11e9-83f9-70d2e1ab4991.png">
<img width="323" alt="Screen Shot 2019-06-13 at 1 31 40 PM" src="https://user-images.githubusercontent.com/9449522/59454268-b2e3ae80-8ddf-11e9-9ec0-5e2b415f46dd.png">
<img width="318" alt="Screen Shot 2019-06-13 at 1 31 47 PM" src="https://user-images.githubusercontent.com/9449522/59454284-b840f900-8ddf-11e9-879d-f144a60087ca.png">

https://xd.adobe.com/spec/9b6bfb40-88d5-4551-5ce9-1a712e457172-ed5a/screen/fa708c63-40b4-46c0-bb7c-4642b01e651c/08-my-chapter/

**Comment by audgster** [comment]
PR Mrged
